<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="PlayniteSDK" Version="6.*" />
		<PackageReference Include="Newtonsoft.Json" Version="13.*" />

		<Reference Include="Microsoft.CSharp" />
		<Reference Include="PresentationCore" />
		<Reference Include="PresentationFramework" />
		<Reference Include="WindowsBase" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="screenshots\" />
	</ItemGroup>

	<ItemGroup>
		<Page Include="SettingsView.xaml">
			<Generator>MSBuild:Compile</Generator>
			<SubType>Designer</SubType>
		</Page>
	</ItemGroup>

</Project>
